# Generated by Django 5.0.6 on 2024-06-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.chat')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='base.user')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='base.user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='belong',
            field=models.ManyToManyField(to='base.user'),
        ),
    ]
