# Generated by Django 5.0.6 on 2024-07-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isOnline',
            new_name='online',
        ),
    ]
