# Generated by Django 5.0.6 on 2024-06-11 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_alter_message_target_alter_message_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='belong',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.person')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.group')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='belong',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='opened_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
