# Generated by Django 5.0.6 on 2024-07-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_chat_unique_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
    ]
