# Generated by Django 5.0.6 on 2024-07-12 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_status_message_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='received',
            new_name='targets',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_reached',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_read',
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('message', 'user')},
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='status',
            name='has_sent',
        ),
    ]
