# Generated by Django 5.0.6 on 2024-07-16 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_received_message_targets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='base.message'),
        ),
    ]
