# Generated by Django 5.0.6 on 2024-06-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_chat_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='belong',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opened_chats', to='base.person'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='target',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to='base.person'),
        ),
    ]
