# Generated by Django 5.0.6 on 2024-07-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_user_pass_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
