# Generated by Django 5.0.6 on 2024-07-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_message_isfile_alter_chat_id_alter_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='file_names', serialize=False, to='base.message')),
                ('name', models.TextField()),
            ],
        ),
    ]
