# Generated by Django 5.0.6 on 2024-07-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='file_names', serialize=False, to='base.message'),
        ),
    ]
