# Generated by Django 5.0.6 on 2024-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_filename_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isFile',
            field=models.TextField(default=False),
        ),
    ]
