# Generated by Django 5.0.6 on 2024-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_pass_phrase_alter_user_public_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='message',
            name='file_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
