# Generated by Django 5.0.6 on 2024-07-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_message_isfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileName',
        ),
    ]
