# Generated by Django 5.0.6 on 2024-07-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='isFile',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='hasReached',
            new_name='has_reached',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='hasRead',
            new_name='has_read',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='hasSent',
            new_name='has_sent',
        ),
    ]
