# Generated by Django 5.0.6 on 2024-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_chat_users_alter_message_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enc_private_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
